# k3s
k3s_version_channel: "stable"
k3s_disable:
  - traefik
  - servicelb

# ArgoCD
argocd_version: "2.13.3"
argocd_namespace: "argocd"

# Git repository (for ArgoCD app-of-apps)
git_repo_url: "https://github.com/paosfocalt/thatch.git"
git_target_revision: "main"
git_argocd_path: "argocd/apps"
