apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: deny-runasroot
spec:
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [pods]
  validations:
    - message: Pod should run as Non Root!
      expression: "object.spec.containers.all(c, c.securityContext.runAsNonRoot==true)"