apiVersion: apps/v1
kind: Deployment
metadata:
  name: thatchbot
  labels:
    app: thatchbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thatchbot
  template:
    metadata:
      labels:
        app: thatchbot
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      containers:
      - name: thatchbot
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000

        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: genai-key
              key: GEMINI_API_KEY

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          periodSeconds: 5

