apiVersion: v1
kind: Service
metadata:
  name: thatchbot-svc
  namespace: thatchbot
spec:
  type: NodePort
  selector:
    app: thatchbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30004

