---
argocd_chart_version: "7.7.23"
argocd_namespace: "argocd"

git_repo_url: "https://github.com/paosfocalt/thatch.git"
git_target_revision: "main"
git_argocd_path: "argocd/apps"

k3s_kubeconfig_path: /etc/rancher/k3s/k3s.yaml
