apiVersion: apps/v1
kind: Deployment
metadata:
  name: thatch-api
  labels:
    app: thatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thatch
  template:
    metadata:
      labels:
        app: thatch
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      containers:
      - name: thatch
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          periodSeconds: 5

